services:
  db:
    image: postgres:14.4
    environment:
      - POSTGRES_USER=postgres  # name of the application database user
      - POSTGRES_PASSWORD=postgres  # name of the application database user
      - POSTGRES_DB=postgres  # name of the application database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - argodbvolume:/var/lib/postgresql/data/
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    command: /var/www/argo/entrypoint.dev.sh
    environment:
      - APPLICATION_PORT=${APPLICATION_PORT:-8014}
    volumes:
      - .:/code
    ports:
      - "${APPLICATION_PORT:-8014}:${APPLICATION_PORT:-8014}"
    depends_on:
      db:
        condition: service_healthy

  elasticsearch:
    image: elasticsearch:7.17.25
    environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8000
      - http.cors.allow-headers=Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With
      - http.cors.allow-credentials=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  argodbvolume:
  elasticsearch:
