version: '3'

services:
  argo-db:
    image: postgres:10.4
    volumes:
      - argodbvolume:/var/lib/postgresql/data/
  argo-web:
    build: .
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - argo-db

volumes:
  argodbvolume:
